# Generated by Django 4.1.2 on 2022-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missing_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('date_missing', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'missing_persons',
            },
        ),
    ]
